---
## playbook to firstly check if ios image is present on the switch and verify its md5 signature if it is
## if it is not present then it uses scp command to copy over and then verify its md5
## fraser clark - 15/11/19


- name: COPY FIRMWARE & VERIFY MD5
  hosts: all
  gather_facts: no

  vars: ## these are the only variables to be changed during future upgrades
    compliant_ios_version: 15.2.4E8
    ios_md5: 2284cbaf62484a2689880b6a4eff7629
    file_name: c2960x-universalk9-mz.152-4.E8.bin

  tasks:

    - name: GATHER SWITCH FACTS
      ios_facts:

    - name: CHECK IOS VERSION ## cancels play if firmware is already compliant
      assert:
        that:
          - "compliant_ios_version != ansible_net_version"
        success_msg: "Firmware requires upgrade. Continuing..."
        fail_msg: "Device on correct firmware"

    ## save output of flash memory as a variable
    - name: show flash
      ios_command:
        commands: 'sh flash:'
      register: shflash 

    ## save running config as a variable
    - name: Show running config
      ios_command:
        commands: show run
      register: showrun

    - debug: ## print the output for human verification
        msg: "show flash: '{{ shflash.stdout[0] }}'"

    - debug: ## print the output for human verification
        msg: "{% if '{{ file_name }}' in shflash.stdout[0] %} IOS Image is present on '{{ inventory_hostname }}' {% else %} beginning image transfer to  '{{inventory_hostname}}' {% endif %}"
 
    - name: VERIFY MD5 IF FILE IS PRESESNT
      block: 

      - name: CHECK MD5
        ios_command:
          commands: verify /md5 flash:{{ file_name }} {{ ios_md5 }}        

      when: "file_name in shflash.stdout[0]" ## the above task will only run if the file is present

    - name: ENABLE SCP IF REQUIRED
      block:

      - name: ENABLE SCP
        ios_command:
          commands: 
            - conf t
            - ip scp server enable
            - exit

      when: "'ip scp server enable' not in showrun.stdout[0]"

    - name: COPY FILE & VERIFY MD5 IF NOT PRESENT
      block: 
      - name: COPY IMAGE TO FLASH ## copies file and names it, sshpass is used to preserve already entered ssh creds using -k
        command: sshpass -p {{ ansible_ssh_pass }} scp ../../static_files/{{ file_name }} ansible.user@{{ inventory_hostname }}:/{{ file_name }}

      - name: CHECK MD5
        ios_command:
          commands: verify /md5 flash:{{ file_name }} {{ ios_md5 }}

      - name: DISABLE SCP
        ios_command:
          commands:
            - conf t
            - no ip scp server enable
            - exit

      when: "file_name not in shflash.stdout[0]" ## the above tasks will only run if the file is NOT present